### ISSUE TITLE
Don't forget about stores having their own inventory system!

### ISSUE THREAD

**Issue by Scifiler-sys** [220118-Reston-NET/Nicolas-Colorado-P0#1]
Your database architecture currently doesn't allow the capability of allowing multiple stores having their own inventory
Ex: Store1 have product 10 pencils, 2 towels
Store2 have product 5 pencils, 2 phones, 3 towels

You'll have problems with getting inventory from a specific store

**Comment by ncolorado10** [comment]
Thank for the heads up. I was still trying to figure out how to create the inventory, but I updated the database and pushed a new diagram.
